import './globals.css'
import Providers from './providers'


export const metadata = {
  title: 'Instituto Rose Reis',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
        <body >
          <Providers>
          {children}
          </Providers>
        </body>
  
     
    </html>
  )
}
